service: toggl-2-toggl
app: toggl-2-toggl
org: marinp1

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 128
  timeout: 5
  versionFunctions: false

package:
  individually: false

functions:
  ping:
    handler: src/handler/index.ping
    description: handler to check if service is available
    events:
      - http:
          path: ping
          method: GET
          # private: true

custom:
  bundle:
    #caching: true # Enable Webpack caching
    linting: false
    sourcemaps: false

plugins:
  - serverless-bundle
  - serverless-offline
