service: toggl-2-toggl
app: toggl-2-toggl
org: marinp1

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  timeout: 5
  versionFunctions: false

package:
  individually: true

functions:
  ping:
    handler: src/handler/ping.ping
    description: handler to check if service is available
    memorySize: 64
    events:
      - http:
          path: ping
          method: GET
          private: true

  metrics:
    handler: src/handler/metrics.getMetrics
    description: fetch current state and metrics
    events:
      - http:
          path: metrics
          method: GET
          private: true

custom:
  bundle:
    caching: false # Enable Webpack caching
    linting: false
    sourcemaps: false
  serverless-offline:
    noAuth: true

plugins:
  - serverless-bundle
  - serverless-offline
