service: toggl-2-toggl
app: toggl-2-toggl
org: marinp1

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
package:
  individually: false

functions:
  hello:
    handler: src/handler.hello

custom:
  bundle:
    caching: true # Enable Webpack caching

plugins:
  - serverless-bundle
