service: toggl-2-toggl
#app: toggl-2-toggl
#org: marinp1

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  timeout: 5
  versionFunctions: false

package:
  individually: true

functions:
  ping:
    handler: src/handler/ping.ping
    description: handler to check if service is available
    memorySize: 64
    events:
      - http:
          path: ping
          method: GET
          private: true

  metrics:
    handler: src/handler/metrics.getMetrics
    description: fetch current state and metrics
    events:
      - http:
          path: metrics
          method: GET
          private: true

  latest:
    handler: src/handler/fetch-entries.fetchLatestEntries
    description: fetch latest entries from Toggl
    events:
      - http:
          path: events/latest/{api_key}
          method: GET
          private: true
          request:
          parameters:
            paths:
              api_key: true

custom:
  webpack:
    webpackConfig: '../webpack.config.js' # Name of webpack configuration file
    includeModules: false
    packager: 'yarn'
  serverless-offline:
    noAuth: true

plugins:
  - serverless-webpack
  - serverless-offline
